### ISSUE TITLE
"RPC: Timed out" on Yosemite

### ISSUE THREAD

**Issue by canadaduane** [codekitchen/dinghy#103]
This is probably because I'm using miquella's https://github.com/miquella/dinghy/commit/dcd28045a8a261ae7b287ac33e2701f02a11e32a docker-machine 0.5.0 patchset. Posting here in case it helps anyone.

I'm repeatedly getting this message from `dinghy up` on OS X 10.10.5:

```
$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Password:
Waiting for NFS daemon...
Mounting NFS /Users/duane
mount: RPC: Timed out
mount: mounting 192.168.99.1:/Users/duane on /Users/duane failed: Bad file descriptor
exit status 110
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:93:in `ssh': Error executing command: ["sudo mount -t nfs 192.168.99.1:/Users/duane /Users/duane -o nfsvers=3,udp,mountport=19611,port=19611,nolock,hard,intr"] (Machine::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:85:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:217:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:81:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'
```

It consistently times out as above. I tried a system restart, but the problem remains.

**Comment by canadaduane** [comment]
Confirmed @miquella's subsequent https://github.com/miquella/dinghy/tree/docker-machine_0.5.0 resolves this issue.
