### ISSUE TITLE
cannot start dinghy

### ISSUE THREAD

**Issue by mattbroekhuis** [codekitchen/dinghy#144]
```
dinghy create --memory=5000 --cpus=4 --disk=40000 --provider=virtualbox
Creating the dinghy VM...
Stopping "dinghy"...
Machine "dinghy" was stopped.
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
NFS mounting failed
Starting the FsEvents daemon
Starting the DNS daemon
Starting the HTTP proxy
Unable to find image 'codekitchen/dinghy-http-proxy:latest' locally
latest: Pulling from codekitchen/dinghy-http-proxy
237d5fcd25cf: Pull complete 
a3ed95caeb02: Pull complete 
d716b6676509: Pull complete 
7317143ee399: Pull complete 
cd437aeec285: Pull complete 
460a06051bae: Pull complete 
a09d61f383e8: Pull complete 
f81f46d95b6b: Pull complete 
b770119cf682: Pull complete 
571b91c24307: Pull complete 
1941b39561be: Pull complete 
38ba920fe749: Pull complete 
c5193176b9f5: Pull complete 
Digest: sha256:2cf1ddd6a408feeb613ce7a77b3cacff746c2127402d999bc0a813dbba025966
Status: Downloaded newer image for codekitchen/dinghy-http-proxy:latest
4f0a3cace8f2dc36fd129e5894fb6f66270fd4b5f964066da24ea042292b242e
  VM: running
 NFS: stopped
FSEV: running
 DNS: stopped
HTTP: running

NFS failed to run
details available in log file: /usr/local/Cellar/dinghy/4.2.0/local/var/dinghy-NFS.output

DNS failed to run
details available in log file: /usr/local/Cellar/dinghy/4.2.0/local/var/dinghy-DNS.output



```

nfs log

```

usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:72:in `exec': No such file or directory - /usr/local/sbin/unfsd (Errno::ENOENT)
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:72:in `run'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `call'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:294:in `start'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:64:in `start'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:9:in `up'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/unfs.rb:28:in `up'
	from /usr/local/Cellar/dinghy/4.2.0/cli/cli.rb:173:in `nfs'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/Cellar/dinghy/4.2.0/bin/_dinghy_command:6:in `<main>'

```

dns log

```
/usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:72:in `exec': No such file or directory - /usr/local/sbin/dnsmasq (Errno::ENOENT)
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:72:in `run'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `call'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
	from /usr/local/Cellar/dinghy/4.2.0/cli/daemons/lib/daemons/application.rb:294:in `start'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:64:in `start'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/daemon.rb:9:in `up'
	from /usr/local/Cellar/dinghy/4.2.0/cli/dinghy/dnsmasq.rb:20:in `up'
	from /usr/local/Cellar/dinghy/4.2.0/cli/cli.rb:220:in `start_services'
	from /usr/local/Cellar/dinghy/4.2.0/cli/cli.rb:57:in `create'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.2.0/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'


```

**Comment by codekitchen** [comment]
That's odd. Dinghy has `unfsd` and `dnsmasq` as dependencies in its homebrew recipe, so they should've been installed by homebrew when you installed dinghy. Does `brew info` show them as installed?

Your brew is at the normal `/usr/local` location, so normally they'd be installed to `/usr/local/sbin`. Were the binaries possibly installed to another location somehow?

**Comment by codekitchen** [comment]
Closing due to comment on https://github.com/codekitchen/dinghy/issues/142#issuecomment-190302909
