### ISSUE TITLE
FsEvents failed to run

### ISSUE THREAD

**Issue by thetalecrafter** [codekitchen/dinghy#154]
version: 4.3.1

Looks like it is trying to require something named `thor` that it can't find.

```
$ dinghy create --provider virtualbox
...
  VM: running
 NFS: running
FSEV: stopped
 DNS: running
HTTP: running

FsEvents failed to run
details available in log file: /usr/local/Cellar/dinghy/4.3.1/local/var/dinghy-FsEvents.output
```

```
$ cat /usr/local/Cellar/dinghy/4.3.1/local/var/dinghy-FsEvents.output
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thor (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.1/lib/fsevents_to_vm/cli.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.1/exe/fsevents_to_vm:1:in `<top (required)>'
	from /usr/local/bin/fsevents_to_vm:23:in `load'
	from /usr/local/bin/fsevents_to_vm:23:in `<main>'
```

```
$ ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
```

**Comment by codekitchen** [comment]
Hm that's an odd one. The `fsevents_to_vm` gem definitely depends on thor https://rubygems.org/gems/fsevents_to_vm

Note that dinghy, like homebrew, uses your OS X system ruby rather than whatever rubies you've installed yourself, to avoid having to deal with arbitrary ruby setups. Does `thor` show as installed in your system ruby with `/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/gem list|grep thor` ?

**Comment by thetalecrafter** [comment]
```
$ /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/gem list|grep thor
thor (0.19.1)
```

**Comment by codekitchen** [comment]
Well so much for the system ruby being a safe haven of consistency! :confused: 

Does installing thor in your other ruby with `gem install thor -v 0.19.1` fix the issue? If so, that'd indicate that it's somehow using the wrong gem set. Dinghy tries to protect against that by unsetting `GEM_HOME` and `GEM_PATH` but perhaps that's not working in this situation somehow.

**Comment by thetalecrafter** [comment]
nope. same issue. Yay Ruby!

**Comment by ryansch** [comment]
The output of `gem env` might be useful here.

**Comment by thetalecrafter** [comment]
```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/avanwagoner/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.2.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.2.0
     - /Users/avanwagoner/.gem/ruby/2.2.0
     - /usr/local/Cellar/ruby/2.2.3/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - ./node_modules/.bin
     - /Applications/Xcode.app/Contents/Developer/usr/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/bin
     - ~/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/MacGPG2/bin
```

**Comment by codekitchen** [comment]
We got it sorted out (at least, working), the gem wasn't completely installed somehow. `sudo /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/gem install thor -v 0.19.1` fixed it. Not sure what to change here. :confused:

**Comment by thetalecrafter** [comment]
Don't worry too much about it if it's just something screwy with my ruby setup.

**Comment by ryansch** [comment]
Excellent. Glad you got it figured out!
