### ISSUE TITLE
Error getting version tag

### ISSUE THREAD

**Issue by heffergm** [codekitchen/dinghy#192]
Suggestions? I'm unclear if this is a legitimate rate limiting error upstream or something else is going on.

```
grant: ~$ dinghy create --provider virtualbox
Creating the dinghy VM...
Error with pre-create check: "Error getting a version tag from the Github API response.\nYou may be getting rate limited by Github."
/usr/local/Cellar/dinghy/4.4.0/cli/dinghy/machine.rb:22:in `create': There was an error creating the VM. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:59:in `create'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```

**Comment by heffergm** [comment]
Resolved itself, so presumably was rate limiting. Sorry for the spam.
