### ISSUE TITLE
NFS failed to run / undefined method 'logfile'

### ISSUE THREAD

**Issue by axsuul** [codekitchen/dinghy#194]
On OS X Yosemite and

```
$ dinghy version                                                                                                                                                                                  
Dinghy 4.4.0
```

I've installed via brew and I have Docker Toolbox and VirtualBox. After doing 

```
$ dinghy create --virtualbox
```

I'm getting this error.

```
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping "dinghy"...
Machine "dinghy" was stopped.
Stopping NFS daemon, this will require sudo
Password:
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
NFS mounting failed
Starting the FsEvents daemon
Starting DNS and HTTP proxy
0e63181584eda4712f3f5960d2ddfd3a04fc2e1f96a304438187394d59319e52
   VM: running
  NFS: stopped
 FSEV: running
PROXY: running

NFS failed to run
/usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:100:in `block in status': undefined method `logfile' for #<Unfs:0x007fa854207778> (NoMethodError)
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:97:in `each'
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:97:in `status'
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:229:in `start_services'
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:79:in `up'
	from /usr/local/Cellar/dinghy/4.4.0/cli/cli.rb:133:in `restart'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.0/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```

Not sure how to debug and it appears to have issues writing to a log. Any suggestions? Thanks so much, looking forward to getting this working as Docker OS X is pretty bad performance-wise :)

**Comment by codekitchen** [comment]
Looks like you've exposed a bug in the error reporting, I'll get that fixed. In the meantime, what it was trying to do was tell you the path to the logfile with more information about the NFS daemon failure. Assuming default install paths, that'll be `/usr/local/Cellar/dinghy/4.4.0/local/var/dinghy-NFS.output`. That file should have more information about why NFS failed to run.

**Comment by axsuul** [comment]
It looks like `unfsd` was missing and for some reason, Homebrew didn't install it along the way. It could've been I had an outdated version of Homebrew. After I updated that and reinstalled dinghy, the issue resolved on its own. Thanks!
