### ISSUE TITLE
Issues after upgrading to MacOS Sierra 

### ISSUE THREAD

**Issue by gabrielqs** [codekitchen/dinghy#209]
Hi guys,

After upgrading to MacOS Sierra I'm looking at the error message below whenever I try to use dinghy. Docker (installed through Docker Toolbox) is working fine.

```
Starting the dinghy VM...
unexpected EOF
/usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:38:in `up': There was an error bringing up the VM. Dinghy cannot continue. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:207:in `start_services'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:79:in `up'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```

I have reinstalled everything from scratch after the upgrade, and so far had no luck with bringing the containers up again.

Any ideas what might be happening? At what file the referred unexpected EOF could be happening?

Thanks,
Gabriel

**Comment by codekitchen** [comment]
Hm that means that `docker-machine start dinghy` is erroring, but the only output it seems to have given is that "unexpected EOF" message which is unusual. Try running that docker-machine command directly to verify if there's any other output.

**Comment by gabrielqs** [comment]
Tried it, but things got really strange... I even got some segfaults from docker, see:
ocker, see below...

Dinghy create was fine:

```
gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker-machine start dinghy
Starting "dinghy"...
(dinghy) Check network to re-create if needed...
(dinghy) Waiting for an IP...
Machine "dinghy" was started.
Waiting for SSH to be available...
Detecting the provisioner...
Started machines may have new IP addresses. You may need to re-run the `docker-machine env` command.
```

But couldnt connect to docker afterwards:

```
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker ps
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```

Configuring env to dinghy

```
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  $(dinghy env)
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  echo $DOCKER_HOST
tcp://192.168.99.101:2376
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker-machine ls
NAME      ACTIVE   DRIVER       STATE     URL                         SWARM   DOCKER    ERRORS
default   -        virtualbox   Running   tcp://192.168.99.100:2376           v1.12.1
dinghy    *        virtualbox   Running   tcp://192.168.99.101:2376           Unknown   Unable to query docker version: Get https://192.168.99.101:2376/v1.15/version: x509: certificate is valid for 192.168.99.102, not 192.168.99.101
```

Docker ps segfaulting...

```
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker ps
[1]    7180 segmentation fault  docker ps
```

Certificate errors all around...

```
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker ps
An error occurred trying to connect: Get https://192.168.99.101:2376/v1.24/containers/json: x509: certificate is valid for 192.168.99.102, not 192.168.99.101
```

Tried to spin up some containers, got some EOF errors again...

```
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  docker-compose up -d app
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "compose/cli/main.py", line 61, in main
  File "compose/cli/main.py", line 113, in perform_command
  File "compose/cli/main.py", line 835, in up
  File "compose/project.py", line 372, in up
  File "compose/project.py", line 539, in warn_for_swarm_mode
  File "site-packages/docker/api/daemon.py", line 33, in info
  File "site-packages/docker/utils/decorators.py", line 47, in inner
  File "site-packages/docker/client.py", line 140, in _get
  File "site-packages/requests/sessions.py", line 477, in get
  File "site-packages/requests/sessions.py", line 465, in request
  File "site-packages/requests/sessions.py", line 573, in send
  File "site-packages/requests/adapters.py", line 370, in send
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 544, in urlopen
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 341, in _make_request
  File "site-packages/requests/packages/urllib3/connectionpool.py", line 761, in _validate_conn
  File "site-packages/requests/packages/urllib3/connection.py", line 253, in connect
  File "site-packages/backports/ssl_match_hostname/__init__.py", line 147, in match_hostname
backports.ssl_match_hostname.CertificateError: hostname '192.168.99.101' doesn't match either of 'localhost', '192.168.99.102'
docker-compose returned -1
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  eval $(docker-machine env)
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/   LFV2-229  dinghy create --provider=virtualbox
Creating the dinghy VM...
Error with pre-create check: "unexpected EOF"
panic: sync: inconsistent mutex state

goroutine 41 [running]:
panic(0xdd93c0, 0xc820242830)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*Mutex).Lock(0xc820010360)
	/usr/local/go/src/sync/mutex.go:75 +0x16d
math/rand.(*lockedSource).Int63(0xc820010360, 0x0)
	/usr/local/go/src/math/rand/rand.go:258 +0x28
math/rand.(*Rand).Int63(0xc82000e490, 0x61315)
	/usr/local/go/src/math/rand/rand.go:46 +0x39
math/rand.(*Rand).Int(0xc82000e490, 0x0)
	/usr/local/go/src/math/rand/rand.go:56 +0x21
math/rand.Int(0xc82013c170)
	/usr/local/go/src/math/rand/rand.go:198 +0x23
net.exchange(0xc8202427f0, 0xa, 0xc8203d5a40, 0x13, 0xc820240001, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:151 +0x405
net.tryOneName(0xc820259600, 0xc8203d5a40, 0x13, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:181 +0x2f3
net.goLookupIPOrder.func1(0xc820259600, 0xc8203d10f0, 0xc820379f20, 0x1)
	/usr/local/go/src/net/dnsclient_unix.go:462 +0x59
created by net.goLookupIPOrder
	/usr/local/go/src/net/dnsclient_unix.go:464 +0x3d0
panic: sync: inconsistent mutex state

goroutine 42 [running]:
panic(0xdd93c0, 0xc8203ec000)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
sync.(*Mutex).Lock(0xc820010360)
	/usr/local/go/src/sync/mutex.go:75 +0x16d
math/rand.(*lockedSource).Int63(0xc820010360, 0x0)
	/usr/local/go/src/math/rand/rand.go:258 +0x28
math/rand.(*Rand).Int63(0xc82000e490, 0x61315)
	/usr/local/go/src/math/rand/rand.go:46 +0x39
math/rand.(*Rand).Int(0xc82000e490, 0x0)
	/usr/local/go/src/math/rand/rand.go:56 +0x21
math/rand.Int(0xc8203e8000)
	/usr/local/go/src/math/rand/rand.go:198 +0x23
net.exchange(0xc8202c9890, 0xa, 0xc8203d5a40, 0x13, 0xc8202c001c, 0x12a05f200, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/dnsclient_unix.go:151 +0x405
net.tryOneName(0xc820259600, 0xc8203d5a40, 0x13, 0x1c, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/go/src/net/dnsclient_unix.go:181 +0x2f3
net.goLookupIPOrder.func1(0xc820259600, 0xc8203d10f0, 0xc820379f20, 0x1c)
	/usr/local/go/src/net/dnsclient_unix.go:462 +0x59
created by net.goLookupIPOrder
	/usr/local/go/src/net/dnsclient_unix.go:464 +0x3d0
/usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:22:in `create': There was an error creating the VM. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:59:in `create'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
```

Running hello world with docker works properly... Feeling kind of lost

```
gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/www/lojaflowv2   LFV2-229  eval $(docker-machine env)
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~/www/lojaflowv2   LFV2-229  docker run ubuntu /bin/echo 'Hello world'
Hello world
```

Any ideas?

**Comment by codekitchen** [comment]
The cert errors are due to the VM's IP address changing, so you need to regenerate the SSL cert. That's covered in the FAQ but Dinghy doesn't yet have code to auto-detect it: https://github.com/codekitchen/dinghy/blob/master/FAQ.md#the-docker-client-reports-errors-like-x509-certificate-is-valid-for-192168xy-not-192168xz

I have no idea about the segfaults in docker and docker-compose, though. Maybe try reinstalling them? Or just fixing the cert issue may make the segfaults go away, possibly.

**Comment by gabrielqs** [comment]
ok, so i decided to destroy dinghy and recreate it...
```
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~  dinghy destroy
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping "dinghy"...
Machine "dinghy" was stopped.
Stopping NFS daemon, this will require sudo
Password:
About to remove dinghy
Are you sure? (y/n): y
Successfully removed dinghy
 gabrielqueirozsilva@Gabriels-MacBook-Pro  ~  dinghy create
Creating the dinghy VM...
Stopping "dinghy"...
Machine "dinghy" was stopped.
Starting NFS daemon, this will require sudo


Waiting for NFS daemon...
Mounting NFS /Users/gabrielqueirozsilva
/usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:112:in `ssh': ssh command failed (RuntimeError)
	from /usr/local/Cellar/dinghy/4.4.1/cli/dinghy/machine.rb:108:in `mount'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:210:in `start_services'
	from /usr/local/Cellar/dinghy/4.4.1/cli/cli.rb:60:in `create'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.4.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
 ✘ gabrielqueirozsilva@Gabriels-MacBook-Pro  ~  dinghy destroy
sh: line 1:  2674 Segmentation fault: 11  docker-machine status dinghy 2>&1
The VM 'dinghy' does not exist in docker-machine.
Run `dinghy create` to create the VM, `dinghy help create` to see available options.
```

Should I take it to the docker forums?

Thanks for your help...
Gabriel

**Comment by codekitchen** [comment]
Yeah those segfaults from the various docker commands are likely the whole problem, and outside the scope of what I can help with. Did you try reinstalling Docker Toolbox?

**Comment by gabrielqs** [comment]
yes, several times... do you usually use the toolbox? any advantages on using the one from Homebrew?

**Comment by codekitchen** [comment]
I've always used homebrew myself, but I have a few co-workers who use Dinghy with Docker Toolbox without issue. Hope you can track it down!

**Comment by gabrielqs** [comment]
got it... thanks a lot, Brian!

**Comment by lmakarov** [comment]
See here for the root cause and a workaround until 1.12.2 is released 
https://github.com/docker/docker/issues/26798#issuecomment-248929611

**Comment by gabrielqs** [comment]
Ok,

**Comment by gabrielqs** [comment]
@lmakarov thanks, glad to know i'm not alone here. the workaround is to stop the ntpd service?

**Comment by gabrielqs** [comment]
Hi Brian,

Dockers issues have been fixed with the suggested workaround, but i still can't get the proxy to run due to the errors described above. Any ideas on how to deal with that one?

Thanks!
Gabriel

**Comment by gabrielqs** [comment]
@codekitchen just a ping to make sure you're following this... it looks like a bug on sierra. Thanks!

**Comment by codekitchen** [comment]
Hm there's something more going on here, dinghy does specify that exact option when running the proxy: https://github.com/codekitchen/dinghy/blob/master/cli/dinghy/http_proxy.rb#L99

Looking at the code in nginx-proxy I don't see anything obvious that might be failing, it just does a simple test to see if `/tmp/docker.sock` is a socket file: https://github.com/jwilder/nginx-proxy/blob/master/docker-entrypoint.sh

This isn't affecting all users who have upgraded to Sierra, quite a few others have upgraded without issue. That always makes tracking it down a lot harder. :/

Did you specify a custom boot2docker image or anything like that? What does your `~/.dinghy/preferences.yml` file look like? I'll see if I can find anybody else who is using Dinghy and Docker Toolbox and has upgraded to Sierra.

**Comment by codekitchen** [comment]
Oh I misread your earlier message, you got that error about the socket when running manually. When running Dinghy you got `**docker: Error while pulling image: Get https://index.docker.io/v1/repositories/codekitchen/dinghy-http-proxy/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: no such host.**`

**Comment by codekitchen** [comment]
That error is saying that the virtualbox VM couldn't resolve DNS for index.docker.io. It may just be a network connectivity hiccup, is it persistent for you? Can you reach index.docker.io from your browser or curl?

**Comment by gabrielqs** [comment]
Hey @codekitchen brian, nevermind. It solved itself, not really sure what happened. Just started working again, maybe it had something to do with the docker crash... Anyway, dinghy is running fine in sierra now. Many thanks again!

**Comment by codekitchen** [comment]
Cool, glad it's working.
