### ISSUE TITLE
Errno::ENOTDIR Exception in fsevents_to_vm/watch.rb:23

### ISSUE THREAD

**Issue by dts** [codekitchen/dinghy#226]
May be a dupey, and this may already be fixed, but I thought I'd post about this.  This exception appears to be causing my fsevents daemon to barf (on dinghy 4.4.1):

```
/Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:23:in `stat': Not a directory - /Users/dstaudigel/Library/Caches/com.tinyspeck.slackmacgap.ShipIt/update.axaVf3l/Slack.app/Contents/Frameworks/ReactiveCocoa.framework/Headers (Errno::ENOTDIR)
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:23:in `build_event'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:13:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:12:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:12:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/rb-fsevent-0.9.6/lib/rb-fsevent/fsevent.rb:45:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/rb-fsevent-0.9.6/lib/rb-fsevent/fsevent.rb:45:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/watch.rb:17:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/lib/fsevents_to_vm/cli.rb:24:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fsevents_to_vm-1.1.2/exe/fsevents_to_vm:4:in `<top (required)>'
	from /usr/local/bin/fsevents_to_vm:23:in `load'
	from /usr/local/bin/fsevents_to_vm:23:in `<main>'
```

Seeing as there already was a rescue call for ENOENT, I added one for ENOTDIR:

```
    def build_event(filepath)
      mtime = Event.format_time(File.stat(filepath).mtime)
      Event.new(filepath, mtime, Time.now)
    rescue Errno::ENOENT
      # TODO: handling delete events is tricky due to race conditions with rapid
      # delete/create.
      nil
    rescue Errno::ENOTDIR
      nil
    end
```

I'm not sure if this will actually fix my relatively flakey fsevents, but it might!

**Comment by codekitchen** [comment]
Oh good catch thanks. I've pushed out a new version of https://github.com/codekitchen/fsevents_to_vm

You can force dinghy to upgrade to the new version without waiting for a new dinghy release by running `sudo /System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin/gem uninstall fsevents_to_vm` and then `dinghy restart`.

**Comment by dts** [comment]
Cool - that was fast.  Thanks!
