### ISSUE TITLE
FSEV stopped every time OSX goes to sleep 

### ISSUE THREAD

**Issue by gastonmorixe** [codekitchen/dinghy#262]
I can't say "every time" but I can say that at least once or twice a day I have to restart dinghy because `FSEV: stopped`

I am using `dinghy 4.6.1` and OSX high sierra (10.13.2)

Thanks

**Comment by codekitchen** [comment]
Usually it'll log something to `/usr/local/Cellar/dinghy/4.6.1/local/var/dinghy-FsEvents.output` (replace 4.6.1 with your current version) when it dies, is there anything logged there?

It's also supposed to restart automatically when it dies, so there may be something wrong there to look into as well.

**Comment by gastonmorixe** [comment]
@codekitchen it's empty

**Comment by gastonmorixe** [comment]
@codekitchen now we have something 
```
Error sending event: Operation timed out - recvfrom(2)
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/buffered_io.rb:65:in `recv'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/buffered_io.rb:65:in `fill'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:272:in `block in ev_do_handle_events'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:268:in `each'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:268:in `ev_do_handle_events'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/event_loop.rb:110:in `ev_select_and_postprocess'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/event_loop.rb:29:in `process'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:225:in `process'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:178:in `block in loop'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:178:in `loop'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:178:in `loop'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/channel.rb:269:in `wait'
	/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/connection/session.rb:425:in `exec!'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/ssh_emit.rb:14:in `event'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/cli.rb:30:in `block in start'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:14:in `block (2 levels) in run'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:12:in `each'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:12:in `block in run'
	/usr/local/Cellar/dinghy/4.6.1/cli/rb-fsevent/lib/rb-fsevent/fsevent.rb:77:in `run'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:17:in `run'
	/usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/cli.rb:24:in `start'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/command.rb:27:in `run'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor.rb:359:in `dispatch'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/base.rb:440:in `start'
	/usr/local/Cellar/dinghy/4.6.1/cli/dinghy/fsevents_to_vm.rb:39:in `run'
	/usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:264:in `call'
	/usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
	/usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
	/usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
	/usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:294:in `start'
	/usr/local/Cellar/dinghy/4.6.1/cli/dinghy/daemon.rb:70:in `start'
	/usr/local/Cellar/dinghy/4.6.1/cli/dinghy/daemon.rb:11:in `up'
	/usr/local/Cellar/dinghy/4.6.1/cli/dinghy/fsevents_to_vm.rb:14:in `up'
	/usr/local/Cellar/dinghy/4.6.1/cli/cli.rb:255:in `start_services'
	/usr/local/Cellar/dinghy/4.6.1/cli/cli.rb:85:in `up'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/command.rb:27:in `run'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor.rb:359:in `dispatch'
	/usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/base.rb:440:in `start'
	/usr/local/bin/_dinghy_command:12:in `<main>'
/usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/transport/session.rb:90:in `rescue in initialize': Net::SSH::ConnectionTimeout (Net::SSH::ConnectionTimeout)
	from /usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh/transport/session.rb:57:in `initialize'
	from /usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh.rb:237:in `new'
	from /usr/local/Cellar/dinghy/4.6.1/cli/net-ssh/lib/net/ssh.rb:237:in `start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/ssh_emit.rb:24:in `ssh'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/ssh_emit.rb:14:in `event'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/cli.rb:30:in `block in start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:14:in `block (2 levels) in run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:12:in `each'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:12:in `block in run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/rb-fsevent/lib/rb-fsevent/fsevent.rb:77:in `run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/watch.rb:17:in `run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/fsevents_to_vm/lib/fsevents_to_vm/cli.rb:24:in `start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/dinghy/fsevents_to_vm.rb:39:in `run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:264:in `call'
	from /usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:264:in `block in start_proc'
	from /usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/daemonize.rb:84:in `call_as_daemon'
	from /usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:268:in `start_proc'
	from /usr/local/Cellar/dinghy/4.6.1/cli/daemons/lib/daemons/application.rb:294:in `start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/dinghy/daemon.rb:70:in `start'
	from /usr/local/Cellar/dinghy/4.6.1/cli/dinghy/daemon.rb:11:in `up'
	from /usr/local/Cellar/dinghy/4.6.1/cli/dinghy/fsevents_to_vm.rb:14:in `up'
	from /usr/local/Cellar/dinghy/4.6.1/cli/cli.rb:255:in `start_services'
	from /usr/local/Cellar/dinghy/4.6.1/cli/cli.rb:85:in `up'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.6.1/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'

```

**Comment by gastonmorixe** [comment]
btw, in the meantime, is there any workaround to restart only FSEV without having to restart everything? Thanks

**Comment by codekitchen** [comment]
Ah that's good info, thanks. I'm curious why this doesn't seem to be a more general problem, but at least it's something we can definitely fix.

There's not currently a way to restart just FSEV, short of constructing the shell command yourself and running it manually, but that's not a bad idea for a feature add.

**Comment by NeoPhi** [comment]
I am also experiencing `FSEV` crashes since upgrading to High Sierra. My `dinghy-FsEvents.output` is identical to the one above.

**Comment by codekitchen** [comment]
I've got a fix on master to handle these SSH errors better without killing the daemon. I'll cut a release in the next couple days.

I see now why the daemon is not restarting when it dies, too, but fixing that is a pretty big change that I'll have to tackle later.

**Comment by gastonmorixe** [comment]
Thanks

**Comment by NeoPhi** [comment]
@codekitchen Any update on that release?

**Comment by codekitchen** [comment]
Hm yeah, the update is that I'm bad at pushing out updates. I've just released v4.6.3 with the change.

**Comment by NeoPhi** [comment]
No worries. I'm giving the new release a try and will let you know if I continue to see the issue. Thank you.

**Comment by NeoPhi** [comment]
Since upgrading to 4.6.3 I've not had any issues with FSEV. Thank you again.
