### ISSUE TITLE
Dinghy broken after brew upgrade to Docker 19.03.0

### ISSUE THREAD

**Issue by ms-ati** [codekitchen/dinghy#289]
After running `brew upgrade` today (Tue July 23 2019), my `dinghy` command is now broken:

```
$ dinghy
/usr/local/Cellar/dinghy/4.6.5/cli/dinghy.rb:100:in `version': undefined method `[]' for nil:NilClass (NoMethodError)
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy.rb:78:in `block in version_check'
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy.rb:77:in `each'
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy.rb:77:in `version_check'
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy.rb:43:in `run_checks'
	from /usr/local/bin/_dinghy_command:11:in `<main>'
```

This may be due to an unparsable version string being returned from `docker --version`:

```
$ docker --version
Docker version unknown-version, build unknown-commit
```

The actual version of Docker is the Homebrew bottled version 19.03.0 installed today:

```
$ brew info docker
docker: stable 19.03.0 (bottled)
Pack, ship and run any application as a lightweight container
https://www.docker.com/
/usr/local/Cellar/docker/19.03.0 (8 files, 79.9MB) *
  Poured from bottle on 2019-07-23 at 14:35:13
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/docker.rb
==> Dependencies
Build: go ✘
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Analytics
install: 37,151 (30 days), 96,146 (90 days), 381,649 (365 days)
install_on_request: 30,748 (30 days), 82,346 (90 days), 325,520 (365 days)
build_error: 0 (30 days)
```

I've also reported this issue to the Hombrew-core formula here:
https://github.com/Homebrew/homebrew-core/issues/42351

**Comment by mediaessenz** [comment]
I can confirm this issue.
My quick workaround was to install the older version (18.09.08) of docker:
```
brew uninstall docker
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/8fbacc1dcbad119d4fbeed49ba6bc3c381bc3c8e/Formula/docker.rb
```
To prevent brew from updating docker at the next `brew upgrade` until this problem is fixed, I pinned the old version by `brew pin docker`

**Comment by codekitchen** [comment]
Thanks for reporting this upstream, it looks like they've already fixed the formula in homebrew with docker version `19.03.0_1`
