### ISSUE TITLE
is the support for xhyve broken now?

### ISSUE THREAD

**Issue by jaequery** [codekitchen/dinghy#296]
I've tried to boot up dinghy+xhyve on a fresh mac and it gave out an error , i forget which, as it's been a couple weeks.

has anyone run into it? it was something to do w/ networking + Docker Machine I think. 

i will try replicate it once i get my hands on the new Mac again but thought i ask in case anyone ran into it.

**Comment by codekitchen** [comment]
I just tried dinghy on Big Sur for the first time, it does look like the xhyve docker-machine driver is broken on Big Sur. There already seems to be an issue filed but no movement from the docker team yet: https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/230

That issue links to the same hyperkit driver discussed the other day in this dinghy issue: https://github.com/codekitchen/dinghy/issues/295

So maybe we need to switch to the hyperkit docker-machine driver, but unfortunately docker doesn't seem to be maintaining that project either, we at least need that PR to be merged in before we can do that. For now it seems your only option is to manually install the fork that has the PR applied, and create the dinghy machine manually. (or use virtualbox etc)

Honestly I'm starting to question whether docker is maintaining docker-machine at all anymore, the main docker-machine project is looking pretty abandoned these days too.

**Comment by jaequery** [comment]
@codekitchen actually this was on Catalina. i haven't even tried Big Sur yet as I hear homebrew is broken on it.

**Comment by FrameBassman** [comment]
Same issue
My environment: 
![image](https://user-images.githubusercontent.com/1880826/102542745-4aa41600-40c3-11eb-80ce-89f99d1e1a10.png)

**Comment by FrameBassman** [comment]
Same issue

**Comment by jaequery** [comment]
Here is the actual error, same error on 2 different macs, High Sierra and Catalina:

```
 ~ dinghy create --provider xhyve

Creating the dinghy VM...
Running pre-create checks...
Creating machine...
(dinghy) Copying /Users/jae/.docker/machine/cache/boot2docker.iso to /Users/jae/.docker/machine/machines/dinghy/boot2docker.iso...
(dinghy) Creating VM...
(dinghy) /dev/disk2          	                               	/Users/jae/.docker/machine/machines/dinghy/b2d-image
(dinghy) "disk2" unmounted.
(dinghy) "disk2" ejected.
(dinghy) Generating 20000MB disk image...
(dinghy) created: /Users/jae/.docker/machine/machines/dinghy/root-volume.sparsebundle
(dinghy) Creating SSH key...
(dinghy) Fix file permission...
(dinghy) Generate UUID...
(dinghy) Convert UUID to MAC address...
(dinghy) Starting dinghy...
(dinghy) Waiting for VM to come online...
(dinghy) Waiting on a pseudo-terminal to be ready... done
(dinghy) Hook up your terminal emulator to /dev/ttys001 in order to connect to your VM
(dinghy) linkname (null)
(dinghy) COM1 connected to /dev/ttys001
Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
/usr/local/Cellar/dinghy/4.6.5/cli/dinghy/system.rb:8:in `system_print': Failure calling `docker-machine create -d xhyve --xhyve-memory-size 2048 --xhyve-cpu-count 1 --xhyve-disk-size 20000 dinghy` (System::Failure)
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy/machine.rb:130:in `system_print'
	from /usr/local/Cellar/dinghy/4.6.5/cli/dinghy/machine.rb:16:in `create'
	from /usr/local/Cellar/dinghy/4.6.5/cli/cli.rb:65:in `create'
	from /usr/local/Cellar/dinghy/4.6.5/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.6.5/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.6.5/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.6.5/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:12:in `<main>'
➜  ~ 
```

**Comment by jaequery** [comment]
Looks like the issue was related to xhyve and referenced here. but I could not get it working following their workaround which was to downgrade the boot2docker version, https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/229.

So instead I just used virtualbox and it's at least working again.
