### ISSUE TITLE
NFS mount fails

### ISSUE THREAD

**Issue by alexvb** [codekitchen/dinghy#44]
Hi,

I installed dinghy on a fresh Yosemite. VM is running but mounting the NFS volume fails with a permission error:

```bash
Bringing machine 'dinghy' up with 'virtualbox' provider...
==> dinghy: Importing base box 'codekitchen/boot2docker'...
==> dinghy: Matching MAC address for NAT networking...
==> dinghy: Checking if box 'codekitchen/boot2docker' is up to date...
==> dinghy: Setting the name of the VM: vagrant_dinghy_1437550383953_7963
==> dinghy: Clearing any previously set network interfaces...
==> dinghy: Preparing network interfaces based on configuration...
    dinghy: Adapter 1: nat
    dinghy: Adapter 2: hostonly
    dinghy: Adapter 3: hostonly
==> dinghy: Forwarding ports...
    dinghy: 2375 => 2375 (adapter 1)
    dinghy: 2376 => 2376 (adapter 1)
    dinghy: 22 => 2222 (adapter 1)
==> dinghy: Running 'pre-boot' VM customizations...
==> dinghy: Booting VM...
==> dinghy: Waiting for machine to boot. This may take a few minutes...
    dinghy: SSH address: 127.0.0.1:2222
    dinghy: SSH username: docker
    dinghy: SSH auth method: private key
    dinghy: Warning: Connection timeout. Retrying...
    dinghy: Warning: Remote connection disconnect. Retrying...
==> dinghy: Machine booted and ready!
==> dinghy: Checking for guest additions in VM...
    dinghy: The guest additions on this VM do not match the installed version of
    dinghy: VirtualBox! In most cases this is fine, but in rare cases it can
    dinghy: prevent things such as shared folders from working properly. If you see
    dinghy: shared folder errors, please make sure the guest additions within the
    dinghy: virtual machine match the version of VirtualBox you have installed on
    dinghy: your host and reload your VM.
    dinghy: 
    dinghy: Guest Additions Version: 4.3.30 r101610
    dinghy: VirtualBox Version: 5.0
==> dinghy: Configuring and enabling network interfaces...
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: private interface is eth2
==> dinghy: route: SIOCDELRT: No such process
==> dinghy: nameserver 10.0.2.3
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: Preparing /Users/testuser NFS mount
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/testuser
mount: 192.168.42.1:/Users/testuser failed, reason given by server: Permission denied
mount: mounting 192.168.42.1:/Users/testuser on /Users/testuser failed: Bad file descriptor
/usr/local/Cellar/dinghy/3.0.2/cli/dinghy/vagrant.rb:40:in `ssh': Error executing command: sudo mount -t nfs 192.168.42.1:/Users/testuser /Users/testuser -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr (RuntimeError)
	from /usr/local/Cellar/dinghy/3.0.2/cli/dinghy/vagrant.rb:59:in `mount'
	from /usr/local/Cellar/dinghy/3.0.2/cli/cli.rb:35:in `up'
	from /usr/local/Cellar/dinghy/3.0.2/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.0.2/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.0.2/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.0.2/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>
```

I tried to ssh into the VM an ran `sudo mount -t ...` manually, but this fails too.

**Comment by joshporter** [comment]
Ran into this issue too. +1 to get it merged in.

**Comment by alexvb** [comment]
This fixed it for me, thanks @simonnordberg.

**Comment by codekitchen** [comment]
looks like this changed in homebrew 4 days ago, causing the breakage: https://github.com/Homebrew/homebrew/pull/40444

@simonnordberg thanks for the fix, can you submit a pull request?

**Comment by cherrry** [comment]
:+1: Ran into this issue as well, thanks @simonnordberg for the fix

**Comment by sroze** [comment]
:+1: for the PR if possible @simonnordberg

**Comment by codekitchen** [comment]
I was getting a lot of pings about this, so I couldn't wait for the PR anymore. Thanks for the help in any case, though, @simonnordberg

**Comment by sroze** [comment]
Great thanks !

**Comment by simonnordberg** [comment]
Sorry guys for not getting back sooner, I've been offline for the past week. Good to see the fix was merged anyway, thanks @codekitchen

**Comment by codekitchen** [comment]
No worries, I appreciate the help

**Comment by stigchristian** [comment]
I got the same issue on 3.0.4:

```
Bringing machine 'dinghy' up with 'virtualbox' provider...
==> dinghy: Box 'codekitchen/boot2docker' could not be found. Attempting to find and install...
    dinghy: Box Provider: virtualbox
    dinghy: Box Version: 1.7.1
==> dinghy: Loading metadata for box 'codekitchen/boot2docker'
    dinghy: URL: https://atlas.hashicorp.com/codekitchen/boot2docker
==> dinghy: Adding box 'codekitchen/boot2docker' (v1.7.1) for provider: virtualbox
    dinghy: Downloading: https://atlas.hashicorp.com/codekitchen/boxes/boot2docker/versions/1.7.1/providers/virtualbox.box
==> dinghy: Successfully added box 'codekitchen/boot2docker' (v1.7.1) for 'virtualbox'!
==> dinghy: Importing base box 'codekitchen/boot2docker'...
==> dinghy: Matching MAC address for NAT networking...
==> dinghy: Checking if box 'codekitchen/boot2docker' is up to date...
==> dinghy: Setting the name of the VM: vagrant_dinghy_1439407463987_9731
==> dinghy: Clearing any previously set network interfaces...
==> dinghy: Preparing network interfaces based on configuration...
    dinghy: Adapter 1: nat
    dinghy: Adapter 2: hostonly
==> dinghy: Forwarding ports...
    dinghy: 2375 => 2375 (adapter 1)
    dinghy: 2376 => 2376 (adapter 1)
    dinghy: 22 => 2222 (adapter 1)
==> dinghy: Running 'pre-boot' VM customizations...
==> dinghy: Booting VM...
==> dinghy: Waiting for machine to boot. This may take a few minutes...
    dinghy: SSH address: 127.0.0.1:2222
    dinghy: SSH username: docker
    dinghy: SSH auth method: private key
    dinghy: Warning: Connection timeout. Retrying...
    dinghy: Warning: Remote connection disconnect. Retrying...
==> dinghy: Machine booted and ready!
==> dinghy: Checking for guest additions in VM...
    dinghy: The guest additions on this VM do not match the installed version of
    dinghy: VirtualBox! In most cases this is fine, but in rare cases it can
    dinghy: prevent things such as shared folders from working properly. If you see
    dinghy: shared folder errors, please make sure the guest additions within the
    dinghy: virtual machine match the version of VirtualBox you have installed on
    dinghy: your host and reload your VM.
    dinghy: 
    dinghy: Guest Additions Version: 4.3.30 r101610
    dinghy: VirtualBox Version: 5.0
==> dinghy: Configuring and enabling network interfaces...
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: private interface is 10.0.2.2
==> dinghy: route: SIOCDELRT: No such process
==> dinghy: kill: you need to specify whom to kill
==> dinghy: nameserver 10.0.2.3
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: Running provisioner: shell...
    dinghy: Running: inline script
==> dinghy: Preparing /Users/stigchristian NFS mount
Starting NFS daemon, this will require sudo
Password:
Waiting for NFS daemon...
Mounting NFS /Users/stigchristian
mount: 192.168.42.1:/Users/stigchristian failed, reason given by server: Permission denied
mount: mounting 192.168.42.1:/Users/stigchristian on /Users/stigchristian failed: Bad file descriptor
/usr/local/Cellar/dinghy/3.0.4/cli/dinghy/vagrant.rb:40:in `ssh': Error executing command: sudo mount -t nfs 192.168.42.1:/Users/stigchristian /Users/stigchristian -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr (RuntimeError)
	from /usr/local/Cellar/dinghy/3.0.4/cli/dinghy/vagrant.rb:59:in `mount'
	from /usr/local/Cellar/dinghy/3.0.4/cli/cli.rb:35:in `up'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.0.4/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>'
```

What am I missing here?

**Comment by Jarown** [comment]
Today, I had the exact same problem. What helped for me was disabling the Firewall-settings (in my case in Norton Security). Just my 2 cents.
