### ISSUE TITLE
Virtualbox 5 Support

### ISSUE THREAD

**Issue by lxe** [codekitchen/dinghy#47]
I install Virtualbox version 5 via Caskroom to use as my dinghy vagrant provider, but when I do `dinghy up`, I see the following error:

```
❯ dinghy up -p virtualbox
The provider 'virtualbox' that was requested to back the machine
'dinghy' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported. Please install one of the supported versions
listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3
/usr/local/Cellar/dinghy/3.0.3/cli/dinghy/vagrant.rb:21:in `up': There was an error bringing up the Vagrant box. Dinghy cannot continue. (RuntimeError)
	from /usr/local/Cellar/dinghy/3.0.3/cli/cli.rb:33:in `up'
	from /usr/local/Cellar/dinghy/3.0.3/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.0.3/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.0.3/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.0.3/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>'
```

**Comment by lxe** [comment]
I'm fairly certain this is a Vagrant error... investigating

**Comment by lxe** [comment]
I think this is because I have an old version of vagrant...

```
❯ vagrant -v
Vagrant 1.7.2
```

The latest one is 1.7.4 as of right now. Sorry for the trouble!
