### ISSUE TITLE
failures seen on mavericks 10.9

### ISSUE THREAD

**Issue by codekitchen** [codekitchen/dinghy#6]
unfs3 fails in some situations when performing a chmod on the NFS share, even when running as root. So far this has never been reproduced in Yosemite, only Mavericks. The error returned is stale NFS file handle.

**Comment by swissmanu** [comment]
is this related to my problem?

dinghy hangs for a long time and quits then with the following message bellow.
i'm on OS X yosemite 10.10.5 (14F27) with virtualbox 4.3.30.

```
alma ~ $ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Password:
Waiting for NFS daemon...
Mounting NFS /Users/alma
mount: RPC: Timed out
mount: mounting 192.168.99.1:/Users/alma on /Users/alma failed: Bad file descriptor
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo mount -t nfs 192.168.99.1:/Users/alma /Users/alma -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr"] (Ssh::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:72:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:6:in `<main>'
```

**Comment by sja87** [comment]
same problem

run after downgrade 5.0.3 to 5.0 and NOT install Extension Pack

**Comment by codekitchen** [comment]
No, this is specifically about Mavericks. I'm going to close this out, it's unlikely we'll ever tackle it at this point when Mavericks is 2 releases behind.
