### ISSUE TITLE
dinghy up fails if not started soon after machine boot

### ISSUE THREAD

**Issue by markoshust** [codekitchen/dinghy#64]
If I wait a while after I boot my mac, `dinghy up` will not bring up the virtualbox vm correctly:

```
Marks-MacBook-Air:~ markshust$ dinghy up
Bringing machine 'dinghy' up with 'virtualbox' provider...
==> dinghy: Checking if box 'codekitchen/boot2docker' is up to date...
==> dinghy: VirtualBox VM is already running.
Stopping NFS daemon, this will require sudo
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/markshust
mount.nfs: an incorrect mount option was specified
mount: mounting 192.168.42.1:/Users/markshust on /Users/markshust failed: Device or resource busy
/usr/local/Cellar/dinghy/3.1.2/cli/dinghy/vagrant.rb:42:in `ssh': Error executing command: sudo mount -t nfs 192.168.42.1:/Users/markshust /Users/markshust -o nfsvers=3,udp,mountport=19321,port=19321,nolock,hard,intr (RuntimeError)
	from /usr/local/Cellar/dinghy/3.1.2/cli/dinghy/vagrant.rb:74:in `mount'
	from /usr/local/Cellar/dinghy/3.1.2/cli/cli.rb:39:in `up'
	from /usr/local/Cellar/dinghy/3.1.2/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/3.1.2/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/3.1.2/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/3.1.2/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/dinghy:5:in `<main>'
```

However, if I execute `dinghy up` immediately after my mac boots, I have no issues. I believe the issue is caused by something that happens in the mac sleep process.

**Comment by markoshust** [comment]
I found that while the above does error out, connecting to the docker daemon afterwards is possible. So perhaps the script needs to stop/exit after the "VirtualBox VM is already running" message, instead of trying to remount the nfs drive.

**Comment by codekitchen** [comment]
yep, this is fixed in the `machine` branch but hasn't been released yet. thanks for the report.
