### ISSUE TITLE
question: docker info reports 1 cpu - how can you allocate all cores?

### ISSUE THREAD

**Issue by rosskevin** [codekitchen/dinghy#68]
I'm trying to test using docker for CI, and using parallel_tests to split and run a process per core (hyperthreading counts as a core), so on my macbook pro, parallel_tests discovers 8 for my 1 hyperthreaded quad core cpu.

When run within docker, it discovers 1.  I would like to allocate as many resources to the CI build process as possible, so this is a bit of a docker question about allocation.  Here's my `docker info`:

```
Containers: 5
Images: 150
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 160
 Dirperm1 Supported: true
Execution Driver: native-0.2
Logging Driver: json-file
Kernel Version: 4.0.9-boot2docker
Operating System: Boot2Docker 1.8.1 (TCL 6.3); master : 7f12e95 - Thu Aug 13 03:24:56 UTC 2015
CPUs: 1
Total Memory: 1.956 GiB
Name: dinghy
ID: MCE7:ZXNE:XIEM:2FFL:BNC7:EMSD:7HCV:NJ43:HZTA:SEOY:5G2A:VJCA
Debug mode (server): true
File Descriptors: 48
Goroutines: 137
System Time: 2015-09-15T20:36:57.946150925Z
EventsListeners: 1
Init SHA1: 
Init Path: /usr/local/bin/docker
Docker Root Dir: /mnt/sda1/var/lib/docker
Labels:
 provider=virtualbox
``

Do I need to setup something with dinghy to see more resources, or can you point me in a direction to read more?

**Comment by codekitchen** [comment]
since docker is running in a VM, the # of CPUs available is governed by the VM configuration. you can set the CPU count on VM creation, see `dinghy help create`. You can also modify the number of CPUs in an existing (stopped) VM directly using the VirtualBox UI, rather than re-creating the VM.

**Comment by rosskevin** [comment]
Thanks, I did a `dinghy halt`, `virtualbox` and edited resources, then `dinghy up`.  I had an error going back up, am I missing something (I've seen this before):

```bash
$ dinghy up
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/kross
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
        from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:69:in `mount'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:181:in `start_services'
        from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:78:in `up'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
        from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
        from /usr/local/bin/_dinghy_command:6:in `<main>'
```
