### ISSUE TITLE
Error creating machine: Error demarshaling the Github API response: json: cannot unmarshal object into Go value of type []struct

### ISSUE THREAD

**Issue by lukebarton** [codekitchen/dinghy#97]
```
~ dinghy create -m 6114 -c 2 -d 80000 -p virtualbox
Creating the dinghy VM...
Error creating machine: Error demarshaling the Github API response: json: cannot unmarshal object into Go value of type []struct { TagName string "json:\"tag_name\"" }
You may be getting rate limited by Github.
You will want to check the provider to make sure the machine and associated resources were properly removed.
/usr/local/Cellar/dinghy/4.0.5/cli/dinghy/machine.rb:14:in `create': There was an error creating the VM. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.0.5/cli/cli.rb:53:in `create'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'
```

I appreciate I may be being rate limited by GitHub (haven't done anything that would cause this recently).

```
 ~ dinghy version
Dinghy 4.0.5
```

**Comment by lukebarton** [comment]
Seems to have resolved itself. No idea what the problem was.

**Comment by ganta** [comment]
Probably it works if set the environment variable `MACHINE_GITHUB_API_TOKEN`.

```
$ docker-machine --help
Usage: docker-machine [OPTIONS] COMMAND [arg...]

Create and manage machines running Docker.

Version: 0.7.0, build a650a40

Author:
  Docker Machine Contributors - <https://github.com/docker/machine>

Options:
  --debug, -D                                           Enable debug mode
  -s, --storage-path "/Users/hideki/.docker/machine"    Configures storage path [$MACHINE_STORAGE_PATH]
  --tls-ca-cert                                         CA to verify remotes against [$MACHINE_TLS_CA_CERT]
  --tls-ca-key                                          Private key to generate certificates [$MACHINE_TLS_CA_KEY]
  --tls-client-cert                                     Client cert to use for TLS [$MACHINE_TLS_CLIENT_CERT]
  --tls-client-key                                      Private key used in client TLS auth [$MACHINE_TLS_CLIENT_KEY]
  --github-api-token                                    Token to use for requests to the Github API [$MACHINE_GITHUB_API_TOKEN]
  --native-ssh                                          Use the native (Go-based) SSH implementation. [$MACHINE_NATIVE_SSH]
  --bugsnag-api-token                                   BugSnag API token for crash reporting [$MACHINE_BUGSNAG_API_TOKEN]
  --help, -h                                            show help
  --version, -v                                         print the version
```

**Comment by lukebarton** [comment]
Good spot. You're 100% correct. Some better messaging around this issue would be an improvement.

**Comment by lukebarton** [comment]
I'll close this and create an improvement
