### ISSUE TITLE
Error executing command: ["sudo umount /Users || true"]

### ISSUE THREAD

**Issue by maxfrigge** [codekitchen/dinghy#99]
After upgrading docker to 1.9 and dinghy to 4.0.5 I cannot start my machine anymore.
Destroying and recreating the machine didn't help either.

```
dinghy already running, restarting...
Stopping the FsEvents daemon
Stopping the dinghy VM...
Stopping NFS daemon, this will require sudo
Stopping the DNS daemon
Starting the dinghy VM...
Starting NFS daemon, this will require sudo
Waiting for NFS daemon...
Mounting NFS /Users/Maxon
Permission denied (publickey,password,keyboard-interactive).
/usr/local/Cellar/dinghy/HEAD/cli/dinghy/ssh.rb:23:in `run': Error executing command: ["sudo umount /Users || true"] (Ssh::CommandFailed)
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:76:in `ssh'
	from /usr/local/Cellar/dinghy/HEAD/cli/dinghy/machine.rb:69:in `mount'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:223:in `start_services'
	from /usr/local/Cellar/dinghy/HEAD/cli/cli.rb:82:in `up'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/HEAD/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'
```

**Comment by maxfrigge** [comment]
Here is some more info

```
dnsmasq: failed to create listening socket for 192.168.151.1: Address already in use
/usr/local/Cellar/dinghy/HEAD/local/var/dinghy-DNS.output (END)
```

```
2015-11-06 09:52 fsevent_watch[1976] (FSEvents.framework) server_gone_StreamRef_callback: ERROR: FSEvents_connect() => unknown error code (124)
2015-11-06 09:52 fsevent_watch[1976] (FSEvents.framework) server_gone_StreamRef_callback: failed to reconnect to server! (kr 0x7c)
/usr/local/Cellar/dinghy/HEAD/local/var/dinghy-FsEvents.output (END)
```

... but I didn't do nottin :_(

**Comment by kacperix** [comment]
In my case when starting dinghy

`dinghy create --cpus=2 --provider=virtualbox`

after a while got this error

```
Creating the dinghy VM...
Machine "dinghy" is already running.
/usr/local/Cellar/dinghy/4.0.5/cli/dinghy/machine.rb:27:in `up': There was an error bringing up the VM. Dinghy cannot continue. (RuntimeError)
	from /usr/local/Cellar/dinghy/4.0.5/cli/cli.rb:184:in `start_services'
	from /usr/local/Cellar/dinghy/4.0.5/cli/cli.rb:54:in `create'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/command.rb:27:in `run'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor.rb:359:in `dispatch'
	from /usr/local/Cellar/dinghy/4.0.5/cli/thor/lib/thor/base.rb:440:in `start'
	from /usr/local/bin/_dinghy_command:6:in `<main>'
```

After halt and up got same error as @maxfrigge

**Comment by maxfrigge** [comment]
@kacperix That happened to me too when i tried to recreate the vm.

**Comment by caleb** [comment]
Using https://github.com/codekitchen/dinghy/pull/101 I managed to get it working... Though as I mention in that PR I still got the error during `dinghy create`, but it worked if I just ran `dinghy up` afterward.

I am still getting the error `DNS: stopped` when running `dinghy up`, and the log says:

```
○ % cat /usr/local/Cellar/dinghy/4.0.5/local/var/dinghy-DNS.output

dnsmasq: failed to create listening socket for 172.16.113.1: Address already in use
```

and indeed `dnsmasq` is already running, and everything seems to work correctly.

**Comment by maxfrigge** [comment]
This is a duplicate of #100 which narrows the problem down to being an incompatibility with docker-machine 0.5.0. 

Im closing this and the discussion should continue there.
